In [10]:
import numpy as np

X = np.array([[0.61187779, 0.36795672, -0.34584511, 0.35499944, 0.76384023,  -0.08459294], [1.09792817, -0.10556685, -0.88420985, -0.05644200, 0.83615511,  0.17833030], [-0.42888210, -2.06554199, -1.05231026, 1.40579467, 1.86205581,  -0.36079627], [0.01606606, 0.15353013, -2.06134086, 0.48556555, -0.00731899,  -0.58839991], [1.40858199, -1.82253402, -0.32959228, 0.69049839, -0.12415830,  2.38552176], [0.09412658, 0.77963648, 0.46942499, 0.01276882, -0.23046872, 0.02936655]])
Y = np.array([[-0.45789500, 0.59539035, 0.11858295, -0.07222311, 0.33363020,  -0.55249914], [0.15646985, 0.59781564, -0.52372170, 0.11564007, 0.23090661, 0.52645867], [-0.10632754, 0.22060951, -0.13695974, 0.64721705, -0.68029373,  -0.19894335], [-0.28566423, 0.29430521, 0.20339449, -0.59801863, -0.56724266,  0.33319746], [-0.43861282, -0.03858079, 0.53929875, 0.44829343, 0.22361869,  0.51411561], [-0.69322330, -0.38904268, -0.60056909, -0.06267378, 0.02835335,  0.05169239]])

Z = np.dot(np.linalg.inv(Y), X).dot(np.linalg.inv(Y.T))

print(Z)


[[ 1.18373632 -0.08894491 -0.08215013  0.8535538  -0.18985997  0.03751803]
 [-0.87803006  0.06076414  1.68182389 -0.93122867  1.3311889   0.55968682]
 [-0.87300919 -0.83788064 -0.25752824 -0.85361492 -0.22164146 -0.73235826]
 [-2.21680984 -1.33334012  1.33768857 -0.1773877  -0.80381664 -0.53696844]
 [-0.61411157  0.88689766 -1.95264945  1.146869   -0.03971687 -1.04316811]
 [-1.17552235 -0.4455343  -0.36528671 -1.01541722  0.73595231 -0.92509316]]
